from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from database import get_db
from models import Project, Ward, Scheme, Complaint
from services.nlp_service import NLPService
from config import settings

router = APIRouter(prefix="/summary", tags=["AI Summary"])
nlp = NLPService(api_key=settings.anthropic_api_key)


@router.post("/{project_id}")
def generate_project_summary(project_id: int, db: Session = Depends(get_db)):
    """
    Generate (or regenerate) a plain-language AI summary for a project.

    Claude generates the summary grounded STRICTLY in structured data:
    score_breakdown, infra evidence, scheme match, and complaint samples.
    The exact input sent to Claude is logged in ai_summary_input_log for auditability.
    """
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    ward = project.ward
    scheme = project.matched_scheme
    complaints = project.complaints[:3] if project.complaints else []

    project_dict = {
        "id": project.id, "name": project.name, "category": project.category,
        "priority_score": project.priority_score,
        "population_affected": project.population_affected,
        "estimated_cost_lakhs": project.estimated_cost_lakhs,
        "net_cost_lakhs": project.net_cost_lakhs,
        "delay_risk": project.delay_risk,
        "infra_evidence": project.infra_evidence,
        "score_breakdown": project.score_breakdown,
        "scheme_cofunding_lakhs": project.scheme_cofunding_lakhs,
    }
    ward_dict = {"name": ward.name if ward else "Unknown"}
    scheme_dict = {
        "name": scheme.name, "short_name": scheme.short_name,
        "cofunding_pct": scheme.cofunding_pct,
    } if scheme else None
    complaint_list = [
        {"translated_text": c.translated_text or c.raw_text, "urgency": c.urgency, "channel": c.channel}
        for c in complaints
    ]

    result = nlp.generate_project_summary(project_dict, ward_dict, scheme_dict, complaint_list)

    # Persist summary and audit log
    project.ai_summary = result.get("summary", "")
    project.ai_summary_input_log = result.get("_input_log", {})
    db.commit()

    return {
        "project_id": project_id,
        "summary": result.get("summary"),
        "model_used": result.get("_model"),
        "source": result.get("_source"),
        "audit_log_stored": True,
        "note": "This summary was generated by Claude, grounded strictly in structured data above. It does not invent numbers.",
    }


@router.get("/{project_id}")
def get_project_summary(project_id: int, db: Session = Depends(get_db)):
    """Get the existing AI summary for a project (without regenerating)."""
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    return {
        "project_id": project_id,
        "summary": project.ai_summary,
        "has_summary": project.ai_summary is not None,
        "audit_log": project.ai_summary_input_log,
    }
