import { useState } from 'react';
import { Sparkles, RefreshCw, AlertCircle, Lock } from 'lucide-react';
import { summaryApi } from '../api/client';
import type { Project } from '../types';

interface Props {
  project: Project;
}

export default function AISummary({ project }: Props) {
  const [summary, setSummary] = useState<string | null>(project.ai_summary);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<string | null>(null);

  const generate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await summaryApi.generate(project.id);
      setSummary(res.data.summary);
      setSource(res.data.source);
    } catch (e: any) {
      setError('Failed to generate summary. Check backend connectivity.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{
      background: 'rgba(139, 92, 246, 0.06)',
      border: '1px solid rgba(139, 92, 246, 0.2)',
      borderRadius: 12, padding: '16px',
    }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Sparkles size={16} color="#8b5cf6" />
          <span style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-primary)' }}>
            AI Executive Summary
          </span>
          <span style={{
            fontSize: '0.65rem', padding: '2px 6px', borderRadius: 99,
            background: 'rgba(139, 92, 246, 0.15)', color: '#a78bfa',
            fontWeight: 600, letterSpacing: '0.05em',
          }}>CLAUDE</span>
        </div>
        <button
          className="btn-ghost"
          onClick={generate}
          disabled={loading}
          style={{ padding: '5px 10px', fontSize: '0.75rem' }}
          aria-label="Generate AI summary"
        >
          <RefreshCw size={12} style={{ animation: loading ? 'spin 1s linear infinite' : 'none' }} />
          {loading ? 'Generating…' : summary ? 'Regenerate' : 'Generate'}
        </button>
      </div>

      {/* Content */}
      {error && (
        <div style={{
          display: 'flex', gap: 8, padding: '10px 12px', borderRadius: 8,
          background: 'rgba(244, 63, 94, 0.1)', border: '1px solid rgba(244, 63, 94, 0.2)',
          fontSize: '0.78rem', color: '#f87171',
        }}>
          <AlertCircle size={14} style={{ flexShrink: 0, marginTop: 1 }} />
          {error}
        </div>
      )}

      {summary ? (
        <div>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>
            {summary}
          </p>
          <div style={{
            display: 'flex', alignItems: 'center', gap: 6, marginTop: 10,
            padding: '6px 10px', borderRadius: 6,
            background: 'rgba(255,255,255,0.04)', border: '1px solid var(--border-subtle)',
          }}>
            <Lock size={11} color="var(--text-muted)" />
            <span style={{ fontSize: '0.68rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
              Generated by Claude, grounded strictly in score breakdown + evidence above.
              {source?.includes('mock') ? ' (Mock — set ANTHROPIC_API_KEY for real AI summaries)' : ' Input logged for auditability.'}
            </span>
          </div>
        </div>
      ) : !loading ? (
        <div style={{
          textAlign: 'center', padding: '20px',
          color: 'var(--text-muted)', fontSize: '0.82rem',
        }}>
          Click "Generate" to get a Claude-powered plain-language summary of this project's evidence and priority rationale.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {[80, 60, 40].map((w, i) => (
            <div key={i} className="shimmer" style={{ height: 16, width: `${w}%` }} />
          ))}
        </div>
      )}

      <style>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
}
